name: Version Checker CI

on:
  push:
    branches: "main"
    paths:
      - 'docker/**'
      - '.github/workflows/**'
      - 'commit.sh'

  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
  CHAT_ID: "${{ secrets.CHAT_ID }}"
  TOPIC_ID: "${{ secrets.TOPIC_ID}}"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}

    - name: "Cancelling duplicate workflow runs"
      uses: styfle/cancel-workflow-action@0.12.0
      with:
        all_but_latest: true
        access_token: ${{ secrets.ACTIONS_TOKEN }}

    - name: Check New Versions
      run: |
            chmod +x ./commit.sh
            ./commit.sh
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Actions"
            git add commit.txt
            commit_hash=$(<"commit.txt")
            if git commit -m "Rimgo Commit: $commit_hash"; then
              git push
            fi




